spring:
  datasource:
#    rewriteBatchedStatements=true  # 开启插入批处理的模式，插入n(1000)条数据，执行一条语句
    url: jdbc:mysql://127.0.0.1:3306/mybatis_plus_heima?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: mpw:PtzcE4pYlzkzK+kKEjBEKQ==
#    password: mpw:F6lu6zIO9PiJnfHIiVX8Ww==
    username: root
    password: 123456
logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss
mybatis-plus:
  type-aliases-package: com.itheima.mp.domain.po
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted # 逻辑删除字段
      logic-delete-value: 1  # 1表示已删除
      logic-not-delete-value: 0 # 0 表示未删除
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
  openapi:
    title: 用户管理接口文档
    description: "用户管理接口文档"
    email: zhanghuyi@qq.com
    concat: 乎乎哥
    url: https://www.baidu.com
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.itheima.mp.controller