#2.配置相关信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: Lins860210SStar

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_

# 配置j2cache
j2cache:
  config-location: j2cache.properties